name = "ZirconGrowth"
uuid = "5085b5e1-578a-4bbf-9dfc-2862bf7461c3"
version = "0.1.0"
authors = ["Boris Kaus <kaus@uni-mainz.de>"]

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
ZirconGrowthGLMakieExt = "GLMakie"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
